sudo: required
language: node_js
branches:
  only:
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
services:
- docker
script:
- yarn -s test:lint
- yarn -s test:jest
- yarn -s docker:build
- yarn -s docker:login
- yarn -s docker:push
- yarn -s aws:build
deploy:
  - provider: elasticbeanstalk
    skip_cleanup: true
    region: us-east-1
    app: Repos
    env: repos-prod
    bucket_name: elasticbeanstalk-us-east-1-328217091811
    bucket_path: repos
    zip_file: web/aws.dockerrun.zip
    on:
      tags: true
  - provider: s3
    skip_cleanup: true
    bucket: static.lquixada.com
    local_dir: web/public
    upload-dir: repos
    on:
      tags: true
