service: repos

custom:
  assets:
    auto: true
    targets:
      - bucket: static.lquixada.com
        prefix: repos
        files:
        - source: dist/public
          globs: '**/*'

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  timeout: 20
  stage: prod
  region: us-east-1
  environment:
    NODE_ENV: production

package:
  exclude:
    - '**'
  include:
    - dist/**
    - node_modules/**
    - package.json

functions:
  api:
    handler: dist/api/lambda.api
    events:
    - http:
        path: /graphql
        method: post
        cors: true
    environment:
      GITHUB_ACCESS_TOKEN: ${file(./.env.js):env.GITHUB_ACCESS_TOKEN}
    
  playground:
    handler: dist/api/lambda.playground
    events:
    - http:
        path: /graphql
        method: get
    environment:
      GITHUB_ACCESS_TOKEN: ${file(./.env.js):env.GITHUB_ACCESS_TOKEN}

  server:
    handler: dist/server/lambda.handler
    events:
      - http: GET /
      - http: GET /{proxy+}

plugins:
- serverless-offline
- serverless-s3-deploy
