service: repos

custom:
  assets:
    auto: true
    targets:
      - bucket: static.lquixada.com
        prefix: repos
        files:
        - source: dist/public
          globs: '**/*'

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  timeout: 20
  stage: prod
  region: us-east-1

package:
  exclude:
    - '**'
  include:
    - dist/**
    - node_modules/**
    - package.json

functions:
  server:
    handler: dist/lambda-server.handler
    events:
      - http: GET /
      - http: GET /{proxy+}
    environment:
      NODE_ENV: production

  api:
    handler: dist/lambda-api.handler
    events:
      - http:
          path: /api
          method: get
          cors: true
      - http:
          path: /api/{proxy+}
          method: get
          cors: true
    environment:
      NODE_ENV: production

plugins:
- serverless-offline
- serverless-s3-deploy
